// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities;

public partial class Catgory
{
    [Key]
    [Column("CatgoryID")]
    public short CatgoryId { get; set; }

    [StringLength(50)]
    public string CatgoryName { get; set; }

    [InverseProperty("Catgory")]
    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}