// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace Entities;

[Table("ORDERS")]
public partial class Order
{
    [Key]
    [Column("ORDER_ID")]
    public short OrderId { get; set; }

    [Column("ORDER_DATE")]
    public DateOnly OrderDate { get; set; }

    [Column("ORDER_SUM")]
    public int? OrderSum { get; set; }

    [Column("USER_ID")]
    public int UserId { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<Orderitem> Orderitems { get; set; } = new List<Orderitem>();

    [ForeignKey("UserId")]
    [InverseProperty("Orders")]
    [JsonIgnore]
    public virtual User User { get; set; }
}