// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace Entities;

[Table("ORDERITEM")]
public partial class Orderitem
{
    [Key]
    [Column("ORDER_ITEM_ID")]
    public short OrderItemId { get; set; }

    [Column("PRODUCT_ID")]
    public short ProductId { get; set; }

    [Column("ORDER_ID")]
    public short OrderId { get; set; }

    [Column("QUNTITY")]
    public int? Quntity { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("Orderitems")]
    [JsonIgnore]
    public virtual Order Order { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("Orderitems")]
    [JsonIgnore]
    public virtual Product Product { get; set; }
}