// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace Entities;

public partial class Product
{
    [Key]
    [Column("ProductID")]
    public short ProductId { get; set; }

    [Column("CatgoryID")]
    public short CatgoryId { get; set; }

    [StringLength(50)]
    public string ProductName { get; set; }

    [StringLength(50)]
    public string ProductDesdription { get; set; }

    public short? Price { get; set; }

    [StringLength(50)]
    public string ImageUrl { get; set; }

    [ForeignKey("CatgoryId")]
    [InverseProperty("Products")]
    //[JsonIgnore]
    public virtual Catgory Catgory { get; set; }

    [InverseProperty("Product")]
    public virtual ICollection<Orderitem> Orderitems { get; set; } = new List<Orderitem>();
}