// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Entities;

[Table("User")]
public partial class User
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Required]
    [Column("USERNAME")]
    [StringLength(50)]
    public string UserName { get; set; }

    [Required]
    [Column("PASSWORD")]
    [StringLength(50)]
    public string Password { get; set; }

    [Column("FIRSTNAME")]
    [StringLength(50)]
    public string FirstName { get; set; }

    [Column("LASTNAME")]
    [StringLength(50)]
    public string LastName { get; set; }
}